name: ExtraGear
version: ${project.version}
authors: [mrCookieSlime, DeathlyPanda]
website: https://thebusybiscuit.github.io/
depend: [Slimefun, CS-CoreLib]

api-version: 1.13

main: me.mrCookieSlime.ExtraGear.ExtraGear
